/control/verbose 2
/geometry/source NA.tg
/run/initialize

/vis/ASCIITree/verbose 13
/vis/drawTree

/geometry/test/run

/vis/open HepRepFile
/vis/drawVolume

/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 100
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow

/gps/particle neutron
/gps/energy 1 MeV
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/halfx 2.5 m
/gps/pos/halfy 2.5 m
/gps/pos/centre 0 0 10 m
/gps/ang/type cos

/run/beamOn 100

/vis/disable
/analysis/setFileName n1MeVInNA.root
/run/verbose 2
/run/printProgress 1000
/run/beamOn 10000

/gps/energy 10 MeV
/analysis/setFileName n10MeVInNA.root
/run/beamOn 10000

/gps/energy 100 MeV
/analysis/setFileName n100MeVInNA.root
/run/beamOn 10000

# shoot neutrons from the side
/gps/energy 1 MeV
/gps/pos/rot1 0 0 1
/gps/pos/centre -2.5 0 12.5 m

/vis/enable
/analysis/setFileName vis.root
/run/beamOn 100

/vis/disable
/analysis/setFileName n1MeVturned.root
/run/beamOn 10000

/gps/energy 10 MeV
/analysis/setFileName n10MeVturned.root
/run/beamOn 10000

/gps/energy 100 MeV
/analysis/setFileName n100MeVturned.root
/run/beamOn 10000
